# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yifan Eric Zhang (张一帆)
description: >- # this means to ignore newlines until "baseurl:"
  Yifan's Personal Website.
baseurl: "/" # the subpath of the site
url: "https://mianhu888.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg

header:
  pages_cn:
    - name: 首页
      slug: /
    - name: 科研
      slug: /research
    - name: 简历
      slug: /CV
    - name: English
      slug: /index_en

  pages_en:
    - name: Home
      slug: /index_en
    - name: Research
      slug: /research_en
    - name: CV
      slug: /CV_en
    - name: 中文版
      slug: /

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: zhangyifan at bnu dot edu dot cn
    - name: Email
      value: ericzh at udel dot edu


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
