# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yifan Eric Zhang
description: >- # this means to ignore newlines until "baseurl:"
  Yifan's Personal Website.
baseurl: "/" # the subpath of the site
url: "https://mianhu888.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: /
    - name: Research
      slug: /research
    - name: CV
      slug: /CV

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: ericzh at udel dot edu


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
